name: Bug Report
description: Reportar um bug
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: Nos conte, o que aconteceu? (Se necessário, descreva o que aparece na tela) O que você esperava que acontecesse?
      placeholder: Nos diga o que você vê!
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Em qual browser você tá vendo o problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Logs relevantes
      description: Por favor, copie e cole qualquer log relevante.
      render: shell
