name: Feature Task
description: Nova funcionalidade para um projeto
title: "✅🌟 "
labels: ["feature", "triage"]
body:
  - type: textarea
    id: o-que-devemos-fazer
    attributes:
      label: "História da atividade"
      description: "Nos conte, o que é suposto o usuario ou sistema fazer com a componente/página/funcionalidade"
      placeholder: "Eu como usuario quero poder criar X que com Y faz Z."
    validations:
      required: true
  - type: textarea
    id: criterios-aceitacao
    attributes:
      label: "Critérios de aceitação:"
      description: "Nos conte como você deseja que o componente/página/funcionalidade seja implementado"
      placeholder: ""
    validations:
      required: false
