name: Feature Task
description: Nova tarefa para uma historia do projeto
title: "Titulo da Tarefa"
labels: ["feature", "triage"]
body:
  - type: textarea
    id: tarefas-issue
    attributes:
      label: "Descrição"
      description: "Elabore mais detalhes caso necessario."
    validations:
      required: false
