name: Feature Task
description: Nova funcionalidade para um projeto
title: "✅🌟 "
labels: ["feature", "triage"]
body:
  - type: textarea
    id: o-que-devemos-fazer
    attributes:
      label: "História da atividade"
      placeholder: "Eu como usuario quero poder criar X que com Y faz Z."
    validations:
      required: true
  - type: textarea
    id: criterios-aceitacao
    attributes:
      label: "Critérios de aceitação:"
      placeholder: "- [] aaaa"
    validations:
      required: false
