name: Feature Task
description: Nova funcionalidade para um projeto
title: "✅🌟 "
labels: ["feature", "triage"]
body:
  - type: textarea
    id: o-que-devemos-fazer
    attributes:
      label: "Descrição da funcionalidade"
      description: "Nos conte, o que é para o componente/página/funcionalidade fazer"
      placeholder: "Nos diga o que você espera que aconteça!"
    validations:
      required: true
  - type: textarea
    id: detalhes-extras
    attributes:
      label: "Detalhes importantes para a implementação"
      description: "Nos conte como você deseja que o componente/página/funcionalidade seja implementado"
      placeholder: "🔃🔃🔃🔃🔃"
    validations:
      required: false
